---
id: rubykaigi-2017
base_name: extension-by-cpp
tags:
- rabbit
- ruby
- extension
- c++
presentation_date: 2017-09-18
version: 2017.9.18.3
licenses:
- CC-BY-SA-4.0
slideshare_id: rubykaigi2017
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
